Module4 task3
htmlacademy-adaptive/917085-mishka-22 pull request #10
Opened 2021-05-15 22:45 UTC by Greenglaz93

2021-05-15 23:55 UTC, wrgraff requested changes
Ну, после формы это изи )
Немножко правок тебе совсем.

2021-05-15 23:55 UTC, wrgraff commented on source/catalog.html
> +  <title>Каталог магазина Mishka</title>
Какое важное изменение ))

2021-05-15 23:55 UTC, wrgraff commented on source/catalog.html
> +      <div class="making__title-wrapper">
А зачем тут обертка?
Вроде бы она даже ничего не делает

2021-05-15 23:55 UTC, wrgraff commented on source/catalog.html
> +        <a class="making__video-button" href="#"></a>
В ссылке нужен текст какой-нибудь

2021-05-15 23:55 UTC, wrgraff commented on source/sass/blocks/making.scss
> +    grid-row: 1 / 2;
Я обычно в таких случаях использую `grid-area`. С ними понятнее делать перестроения, когда они довольно сложные и непоследовательные.

Но это как захочешь )

2021-05-15 23:55 UTC, wrgraff commented on source/catalog.html
> +  <main class="page__main page-catalog">
Я так понял, что `page-catalog` тебе нужен для управления размерами отступов между блоками каталога. Это ок.
Но зачем удалять `page-main`? Тем более, ты через него оформляла заголовок с серым фоном. А ведь он тут по стилю абсолютно такой же, как и на странице формы.
Все те же элементы можно и тут использовать.

А `page-catalog` пускай уж тогда будет сам по себе отвечать за отступ от видео =)

2021-05-16 07:20 UTC, Greenglaz93 commented on source/sass/blocks/making.scss
> +    grid-row: 1 / 2;
Мне не сложно работать с таким, но ок, попробую что-то новенькое и применю grid-area :)

2021-05-16 10:20 UTC, wrgraff commented on source/sass/blocks/making.scss
> +    grid-row: 1 / 2;
Ну это так, делюсь просто =)

2021-05-16 10:20 UTC, wrgraff approved these changes

2021-05-16 10:20 UTC, merged