Module3 task1
htmlacademy-adaptive/917085-mishka-22 pull request #5
Opened 2021-04-09 20:31 UTC by Greenglaz93

2021-04-10 09:55 UTC, wrgraff requested changes
Вообще, ты молодец.
Может быть, паддингов чуть больше хочется видеть.

2021-04-10 09:55 UTC, wrgraff commented on source/sass/style.scss
> +@import "components/toggles.scss";
Какой еще компонентс )
До компонентс еще 2 интенсива! =)

Занятно, что ты их так выделила, но сейчас у нас только блоки.
Эти блоки -- маленькие, без элементов, но тоже блоки

2021-04-10 09:55 UTC, wrgraff commented on source/sass/global/variables.scss
> +$grey-241: #f1f1f1;
Это ты как такие цифры вычислила? ))

2021-04-10 09:55 UTC, wrgraff commented on source/sass/global/variables.scss
> +$primary-400: $primary;
Я вот обычно если так делаю, то наоборот.
Сперва палитра полностью, а потом базовый цвет и ему задается один из оттенков палитры.
Но это мой метод, у тебя свой: с другой то стороны, обычно сперва базовый цвет берется, а затем палитра от него строится.

В общем, молодец.

2021-04-10 09:55 UTC, wrgraff commented on source/sass/global/mixins.scss
> +@mixin pseudo($display: block, $pos: absolute, $content: "") {
Если позишн `absolute`, то он и так отображается как `display: block`.
Получается, у тебя в значениях по умолчанию бесполезный код уже есть )

2021-04-10 09:55 UTC, wrgraff commented on source/sass/components/button.scss
> +  text-transform: uppercase;
У кнопок, сделанных через `<button>`, есть еще браузерный шрифт.
Можно переписать это свойство так, чтобы он наследовался.

2021-04-10 09:55 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +  @include clear-list;
Вот строго говоря, по БЭМу за правку отступов должны отвечать только элементы, а не блоки.
Даже за сброс. Потому что иначе придется мучиться с порядком подключения, ведь сброс стилей в каком-то блоке может перебить значение отступов в элементе.

2021-04-10 09:55 UTC, wrgraff commented on source/sass/blocks/page.scss
> +  max-height: 100%;
Не рановато за позиционирование то взялась?

2021-04-10 09:55 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +  background-image: url("../../img/bg/hero-mobile@2x.jpg");
Путь должен быть указан относительно скомпилированного файла, а не препроцессорного

2021-04-10 10:06 UTC, wrgraff commented on source/index.html
> +        <a class="toggles__item toggles__item--next" href="#" aria-label="Показать следующий отзыв">
Я как-то проглядел этот момент. Чего это у нас тут ссылки вообще?
Почему не обычные кнопки?

2021-04-10 17:42 UTC, Greenglaz93 commented on source/sass/global/variables.scss
> +$grey-241: #f1f1f1;
grey 229 = #e5e5e5 = rgb(229, 229, 229) мне так удобнее в них не путаться..

2021-04-10 18:00 UTC, Greenglaz93 commented on source/index.html
> +        <a class="toggles__item toggles__item--next" href="#" aria-label="Показать следующий отзыв">
не проглядел, там были кнопки..что-то я задумывалась, уже не вспомню, всё вернула

2021-04-11 09:04 UTC, wrgraff commented on source/sass/global/variables.scss
> +$grey-241: #f1f1f1;
О_о
Вон оно как, оказывается...

2021-04-11 09:06 UTC, wrgraff commented on source/index.html
> +        <a class="toggles__item toggles__item--next" href="#" aria-label="Показать следующий отзыв">
Ааа, там весь документ подсвечен как измененный из-за табуляции )

2021-04-11 09:06 UTC, wrgraff commented on source/sass/blocks/page.scss
> +  max-height: 100%;
Ну удалять то не обязательно, я ж просто спросил )

2021-04-11 09:08 UTC, wrgraff approved these changes

2021-04-11 09:08 UTC, merged