Module4 task1
htmlacademy-adaptive/917085-mishka-22 pull request #8
Opened 2021-04-25 15:24 UTC by Greenglaz93

2021-04-26 21:33 UTC, wrgraff reviewed
Не забывай работать не только на том разрешении, что указано в критериях и макете.
Еще нужно обеспечить нормальные переходы и тянущиеся фоны.
Удобнее вообще наоборот сделать чуть шире область, чтобы видеть все ли хорошо центрируется.

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  }
Когда флекс превращается в грид это ооооочень сомнительно.
Большая вероятность что что-то пошло не так.

Вот смотри, например, этот контент ведь тоже очень хорошо ложится в сетку с равными колонками, и по сетке построен (текст то там не по контенту ужат):
![изображение](https://user-images.githubusercontent.com/37917037/116149983-75dee780-a6eb-11eb-86ee-4793e7c95d08.png)
![изображение](https://user-images.githubusercontent.com/37917037/116150004-7bd4c880-a6eb-11eb-834d-66afff8757c6.png)

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +.contacts .content-wrapper {
У тебя не может быть блок `.content-wrapper` в файле для стилей блока `.contacts`

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +}
Ты не можешь ограничить всю секцию по ширине, потому что карта должна тянуться от края до края экрана

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +}
Вообще, стили у этих секций одинаковые, зачем же им разные классы?
Они могли бы быть одним и тем же элементом

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +}
Хэдер тоже нельзя по ширине ограничивать, в нем должен фон тянуться.
И на мобильном еще и зеленые кнопки тянуться должны.

А так ничего не будет тянуться

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +}
А тебе не кажется, что это как-то не очень правильно, что у тебя положение в сетке задается элементам блока `main-nav`, а сама сетка — в `page-header`?
Было бы логчнее, если бы сетка задавалась блоком, а то его самостоятельность под вопросом: вытащи его из `page-header`, и сетку сдует как и не было...

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +    grid-row: 2 / 3;
Не понимаю я, как вы с этими `2 / 3` и `3 / 8` ориентируетесь в сложных сетках...
Я вот себе templete-areas пишу, если перемещения элементов большие.

Например так (это из моего проекта, так что не ищи подсказки, их там нет, просто пример с именованием областей грида):
![изображение](https://user-images.githubusercontent.com/37917037/116151603-7d06f500-a6ed-11eb-9f5c-71d677a0b8d7.png)

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/page.scss
>    font-family: "Open Sans", "Arial", sans-serif;
Шрифты, кстати, что-то не подключаются

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/products.scss
> +      top: 21px;
Ой, их же можно одинаковыми сделать и поставить в одно и тоже место.
Ты видишь так:
![изображение](https://user-images.githubusercontent.com/37917037/116151936-f1da2f00-a6ed-11eb-9dd5-5b17ad2c3247.png)

А можно так, 2 квадрата в одном месте со вписанной картинкой:
![изображение](https://user-images.githubusercontent.com/37917037/116152059-1cc48300-a6ee-11eb-9ddf-9ca1fc88fc9a.png)

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  width: 255px;
А откуда этот размер магический?
А что, если у нас будет другой автор длинный. Неужели для Константина там бы не хватило места в одной строке?
![изображение](https://user-images.githubusercontent.com/37917037/116152470-a1170600-a6ee-11eb-8809-4a5e252b34fa.png)

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  width: 260px;
Там кстати ширина кнопки не по прихоти размер меняет.
Она совпадает с размером кнопок переключения всегда. Можно было бы это как-то красиво в грид вписать попробовать (но может и не выйдет)

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/toggles.scss
> +    transform: rotate(180deg);
Ага, я так тоже делал, а потом решил, что трансформ ради этого привлекать какой-то перегиб =)

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +.site-list__item:not(:nth-child(even)) {
Что за жуть, почему не просто `:not(:last-child)`?

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +    margin-right: 36px;
Можно еще ставить левый отступ для `.site-list__item + .site-list__item`

2021-04-26 21:33 UTC, wrgraff commented on source/sass/blocks/top-offer.scss
> +    top: -120px;
Вот тут не очень нравится мне. А если заголовок станет в 2 строки?
Лучше бы его привязать к контейнеру общему с заголовком

2021-04-26 21:33 UTC, wrgraff commented on source/sass/global/global.scss
> +@import "viewports.scss";
Не надо его сюда импортить.
Просто импортируй в правильном порядке файлы в основном файле. Сперва все переменные, потом миксины и вот уже потом глобальные стили

2021-04-26 21:33 UTC, wrgraff commented on source/sass/global/global.scss
> +}
С точки зрения БЭМа это все-таки блок, ему бы в свой файл блока переехать

2021-05-09 13:33 UTC, Greenglaz93 commented on source/sass/blocks/contacts.scss
> +  grid-template-columns: max-content max-content;
адрес вроде как  у нас стоял в исключениях при употреблении <br>, ну я голову пока всё равно сломала без них)

2021-05-09 17:34 UTC, wrgraff commented on source/index.html
> +            <input class="add-to-cart__radio visually-hidden" type="radio" name="size" id="size_l" value="l">
Лучше настоящий инпут позиционировать поверх нарисованного и делать его такого же размера, но прозрачным.

2021-05-09 17:34 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  grid-template-columns: max-content max-content;
А что за исключения?
Сами переносы то ты можешь использовать, это не проблема. Но при их удалении текст не должен сломать сетку.

2021-05-09 17:56 UTC, wrgraff requested changes
Нашел один все-таки довольно критичный момент.
А вообще очень бодро поработала, прям молодец!

2021-05-09 17:56 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  grid-template-columns: 76px 184px;
Можно еще оставить `column-gap`, или, если это невозможно, поставить какой-то внутренний отступ (или внешний) просто на всякий пожарный, чтобы колонки не слиплись текстом.

2021-05-09 17:56 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +  width: 100vw;
Ой. Не надо так писать, `vw` очень глючная ширина, она может иногда считать скроллбар. И тогда у тебя будет всегда скролл горизонтальный.

если оно тут нужно для чего-то, используй проценты тогда. 100% дадут всю ширину тоже.
И лучше на `.page__main`, то есть на элемент, а не на блок применять ширину.

2021-05-09 17:56 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> -}
Ширина все-таки делала одну вещь полезную.
Она не позволила бы тексту залезть под кнопки:
<img width="912" alt="изображение" src="https://user-images.githubusercontent.com/37917037/117581806-61491900-b107-11eb-9340-1dca9ebe4392.png">

Ты можешь это паддингом исправить, оттолкнувшись на размер, равный ширине кнопок.

2021-05-09 17:56 UTC, wrgraff commented on source/sass/global/mixins.scss
> +@mixin content-wrapper($width: 260px, $padding: 0 30px) {
А зачем параметры прописаны, если ты их не используешь внутри

2021-05-09 17:56 UTC, wrgraff commented on source/sass/global/mixins.scss
> +  box-sizing: content-box;
Не меняй `box-sizing` "по требованию". У тебя должен быть или один метод подсчета размеров, или другой. Разных быть не должно, а то так можно запутаться легко.

2021-05-09 17:56 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  width: 320px;
Надо проследить, чтобы у тебя в блоках не было ширин и отступов внешних.
Если они есть, переносить их в элементы родительского блока.

2021-05-11 10:34 UTC, wrgraff approved these changes

2021-05-11 10:34 UTC, merged