Module4 task2
htmlacademy-adaptive/917085-mishka-22 pull request #9
Opened 2021-05-13 18:29 UTC by Greenglaz93

2021-05-13 22:35 UTC, wrgraff requested changes
В общем, я записал тебе ревью =)
Залил [на ютуб](https://youtu.be/uufongk9yV0), на момент отправки оно еще публикуется, но завтра должно быть точно доступно в хорошем качестве.

Думаю, в итоге так будет нагляднее и понятнее. И быстрее.

2021-05-13 22:35 UTC, wrgraff commented on source/sass/style.scss
> +@import "form/field.scss";
Это не по критериям. У нас заданы другие правила: один блок — один файл, структура плоская.
Вообще, БЭМ не предполагает и сам по себе такой структуры. Все блоки независимы и равнозначны.

Можно их как-то группировать и размечать комментариями для удобства, но не более того.

2021-05-13 22:35 UTC, wrgraff commented on source/sass/form/form-group.scss
> +  }
Лучше задавать какие-то параметры позиционирования. Иначе элемент же просто встает по месту. А потом тебе понадобится его подвигать, а к чему он окажется привязан может быть сюрпризом )

2021-05-15 01:03 UTC, Greenglaz93 commented
полосочки после названий форм на мобилке добью попозже, выбесили на ночь глядя

2021-05-15 10:25 UTC, wrgraff requested changes
Все гуд. По полоскам на самом деле все довольно просто, я там подсказку дал, их быстро можно доделать

2021-05-15 10:25 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +      top: 26px;
Будет сложно реализовать эту полоску, делая ее абсолютом.
Ты же в курсе, что псевдоэлемент ≠ абсолют? =)

Смотри, тут типичная задача:
У тебя есть текст, который занимает столько места, сколько ему надо. Затем небольшой отступ и полоска, занимающая все свободное пространство.
Какая такая у нас есть технология, которая решает такие задачи на раз-два-три? (Ответ в личку скинь прежде чем начать делать)

2021-05-15 18:45 UTC, wrgraff approved these changes

2021-05-15 18:45 UTC, merged